version: 0.2
phases:
  install:
  runtime-versions:
  python: 3.8
    commands:
      - pip install awscli boto3
  pre_build:
    commands:
      - echo "Retrieving GitHub repository URL and token from DynamoDB"
      - &gt;
      REPO_AND_TOKEN=$(aws dynamodb get-item --table-name my-dynamodb-table
      --key '{"id": {"S": "primary-key-value"}}'
      --query 'Item.repo_url.S,Item.token.S' --output text)
      - REPO_URL=$(echo $REPO_AND_TOKEN | cut -d' ' -f1)
      - GITHUB_TOKEN=$(echo $REPO_AND_TOKEN | cut -d' ' -f2)
      - echo "Cloning GitHub repository"
      - git clone $REPO_URL
  build:
    commands:
      - echo "Zipping the repository"
      - REPO_NAME=$(basename $REPO_URL .git)
      - cd $REPO_NAME
      - zip -r ../$REPO_NAME.zip .
      - cd ..
  post_build:
    commands:
      - echo "Uploading the zip to S3 bucket"
      - aws s3 cp $REPO_NAME.zip s3://my-s3-bucket-x/$REPO_NAME.zip
artifacts:
  files:
    - $REPO_NAME.zip
