---
version: 0.2
env:
  variables:
    REPO_URL: https://github.com/mddabhi93/helloworld
    SQS_QUEUE: 'https://sqs.us-east-1.amazonaws.com/036192280692/my-sqs'
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
#      - pip install awscli boto3
#      - echo "Retrieving GitHub repository URL and token from DynamoDB"
#      - REPO_AND_TOKEN=$(aws dynamodb get-item --table-name my-dynamodb-table
#        --key'{"id":{"S":"primary-key-value"}}'
#        --query'Item.repo_url.S,Item.token.S' --output text)
#      - REPO_URL=$(echo $REPO_AND_TOKEN | cut -d' ' -f1)
#      - GITHUB_TOKEN=$(echo $REPO_AND_TOKEN | cut -d' ' -f2)
#      - echo "Cloning GitHub repository"
      - git clone https://github.com/mddabhi93/helloworld
  build:
    commands:
      - echo "Zipping the repository"
      - REPO_NAME=$(basename $REPO_URL .git)
      - cd $REPO_NAME
      - zip -r ../$REPO_NAME.zip .
      - cd ..
  post_build:
    commands:
      - echo "Uploading the zip to S3 bucket"
      - aws s3 cp $REPO_NAME.zip s3://my-s3-bucket-x/$REPO_NAME.zip
      - gem install bundler
      - bundle install
    finally:
      - aws sqs send-message --queue-url $SQS_QUEUE --message-body "$(sed -e
        's/insert-build-step/install/g' -e
        s/insert-build-status/${CODEBUILD_BUILD_SUCCEEDING}/g
        .build/sqs-send_message_body.json)" --message-attributes "$(sed -e
        s/insert-epoch/${CODEBUILD_START_TIME}/g -e
        s/insert-logpath/${CODEBUILD_LOG_PATH}/g
        .build/sqs-send_message_attributes.json)"
